language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install .
  - pip install -U pylint coverage pep8 pydocstyle
# command to run tests
script: 
  - py.test
  - pep8 rbtr
  - pylint --reports=no --rcfile .pylintrc rbtr
  - pydocstyle rbtr
  - coverage run --source rbtr/ -m py.test -v

